Document: pcapfix
Title: Debian pcapfix Manual
Author: <insert document author here>
Abstract: This manual describes what pcapfix is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pcapfix/pcapfix.sgml.gz

Format: postscript
Files: /usr/share/doc/pcapfix/pcapfix.ps.gz

Format: text
Files: /usr/share/doc/pcapfix/pcapfix.text.gz

Format: HTML
Index: /usr/share/doc/pcapfix/html/index.html
Files: /usr/share/doc/pcapfix/html/*.html
